extends MenuScreen
## Crédits : générique qui défile lentement (en boucle). ↑ / ↓ ou la molette
## accélèrent / inversent le défilement.

const SPEED := 34.0  # px/s
const WIDTH := 700.0
const CLIP_TOP := 112.0
const CLIP_H := 500.0
const EDGE := 70.0  # hauteur des fondus haut / bas

## [genre, texte français, texte anglais] (sans anglais : même texte, noms propres).
const LINES := [
	["h1", "CLAUDE OF DUTY ZOMBIE"],
	["p", "Survie coopérative en bunker, de 1 à 4 joueurs.", "Co-op bunker survival, for 1 to 4 players."],
	["gap"],
	["role", "CONÇU ET DÉVELOPPÉ PAR", "DESIGNED AND DEVELOPED BY"],
	["name", "Claude (Anthropic)"],
	["p", "pour Valentin", "for Valentin"],
	["gap"],
	["role", "PROGRAMMATION · CONCEPTION DE JEU", "PROGRAMMING · GAME DESIGN"],
	["name", "Claude"],
	["role", "DIRECTION ARTISTIQUE · ÉCLAIRAGE", "ART DIRECTION · LIGHTING"],
	["name", "Claude"],
	["role", "CONCEPTION SONORE · MUSIQUE", "SOUND DESIGN · MUSIC"],
	["name", "Claude"],
	["gap"],
	["role", "MOTEUR", "ENGINE"],
	["name", "Godot Engine 4"],
	["p", "Moteur libre et open source (licence MIT) — godotengine.org", "Free and open source engine (MIT license) — godotengine.org"],
	["gap"],
	["role", "SONS", "SOUNDS"],
	["p", "Tirs, rechargements, couteau, impacts, grenades, chiens de l'enfer, barricades, voix des zombies et du joueur : enregistrements libres de droits (CC0, domaine public) de freesound.org, retravaillés pour le jeu.",
		"Gunshots, reloads, knife, impacts, grenades, hellhounds, barriers, zombie and player voices: royalty-free recordings (CC0, public domain) from freesound.org, reworked for the game."],
	["p", "Merci à qubodup, serøutōnin--deprivəd, morganpurkis, SuperPhat, LeMudCrab, LilMati, tonsil5, Under7dude, ArriGD, haratman, PaulMorek, unfa, coldvet, martian, kyles, Paul368, roboroo et tous les auteurs listés dans docs/ASSETS.md.",
		"Thanks to qubodup, serøutōnin--deprivəd, morganpurkis, SuperPhat, LeMudCrab, LilMati, tonsil5, Under7dude, ArriGD, haratman, PaulMorek, unfa, coldvet, martian, kyles, Paul368, roboroo and every author listed in docs/ASSETS.md."],
	["p", "Musiques, ambiances, annonces, jingles et interface : synthétisés par du code.",
		"Music, ambiences, announcer, jingles and interface: synthesized by code."],
	["role", "VOIX DES PERSONNAGES", "CHARACTER VOICES"],
	["p", "Callahan, Orlov, Arakawa et Weissmann : personnages et répliques originaux, voix de synthèse générées hors ligne avec Chatterbox Multilingual (Resemble AI, licence MIT) à partir de voix de référence synthétiques Kokoro-82M (hexgrad, licence Apache 2.0). Aucune voix de personne réelle n'est imitée.",
		"Callahan, Orlov, Arakawa and Weissmann: original characters and lines, synthetic voices generated offline with Chatterbox Multilingual (Resemble AI, MIT license) from synthetic Kokoro-82M reference voices (hexgrad, Apache 2.0 license). No real person's voice is imitated."],
	["role", "GRAPHISMES", "GRAPHICS"],
	["p", "100 % procéduraux : maillages, matériaux, textures et effets générés par des shaders et des scripts. Aucune image externe.",
		"100% procedural: meshes, materials, textures and effects generated by shaders and scripts. No external images."],
	["role", "POLICES", "FONTS"],
	["p", "Polices système de la machine du joueur.", "System fonts of the player's computer."],
	["gap"],
	["role", "REMERCIEMENTS", "THANKS"],
	["name", "Valentin"],
	["p", "pour l'idée, les parties de test et la patience.", "for the idea, the test games and the patience."],
	["name", "La communauté Godot", "The Godot community"],
	["p", "pour un moteur qui se laisse tout construire en code.", "for an engine that lets you build everything in code."],
	["name", "Les survivants", "The survivors"],
	["p", "qui tiendront jusqu'à la manche 100. Ou presque.", "who will hold out until round 100. Or nearly."],
	["gap"],
	["gap"],
	["p", "Aucun zombie n'a été maltraité pendant le développement.", "No zombies were harmed during development."],
	["p", "Les autres, si.", "The others were."],
	["gap"],
	["gap"],
]

var _clip: Control
var _roll: VBoxContainer
var _boost := 1.0


func enter(_args := {}) -> void:
	var t := title(Lang.t("CRÉDITS", "CREDITS"), 46)
	t.position = Vector2(96, 34)
	add_child(t)
	_clip = Control.new()
	_clip.clip_contents = true
	_clip.position = Vector2(96, CLIP_TOP)
	_clip.size = Vector2(WIDTH, CLIP_H)
	_clip.mouse_filter = Control.MOUSE_FILTER_PASS
	add_child(_clip)
	_roll = vbox(6)
	_roll.custom_minimum_size = Vector2(WIDTH, 0)
	_roll.size.x = WIDTH
	_clip.add_child(_roll)
	for l in LINES:
		_roll.add_child(_line(l))
	_roll.position.y = CLIP_H * 0.45
	var back_btn := button(Lang.t("RETOUR", "BACK"), back, Lang.t("↑ ↓ : faire défiler.", "↑ ↓: scroll."))
	back_btn.set_anchors_preset(Control.PRESET_BOTTOM_LEFT)
	back_btn.offset_left = 96
	back_btn.offset_top = -120
	back_btn.offset_bottom = -76
	add_child(back_btn)
	focus_later(back_btn)


## Texte d'une ligne du générique dans la langue du joueur.
static func line_text(l: Array) -> String:
	if l.size() < 2:
		return ""
	return Lang.t(l[1], l[2] if l.size() > 2 else l[1])


func _line(l: Array) -> Control:
	var s := line_text(l)
	match l[0]:
		"h1":
			var h := MenuStyle.title(s, 40)
			h.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			return h
		"role":
			var r := UiStyle.label(s, 16, Color(0.66, 0.16, 0.1), "impact")
			r.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			return r
		"name":
			var n := UiStyle.label(s, 28, UiStyle.BONE, "impact")
			n.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			return n
		"p":
			var p := UiStyle.label(s, 18, UiStyle.DIM)
			p.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
			p.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
			p.custom_minimum_size = Vector2(WIDTH, 0)
			return p
	var g := Control.new()
	g.custom_minimum_size = Vector2(0, 34)
	return g


func _process(delta: float) -> void:
	var dir := 1.0
	if Input.is_action_pressed("ui_down"):
		_boost = 7.0
	elif Input.is_action_pressed("ui_up"):
		_boost = 7.0
		dir = -1.0
	else:
		_boost = move_toward(_boost, 1.0, delta * 8.0)
	_roll.position.y -= SPEED * _boost * dir * delta
	var h := _roll.size.y
	if _roll.position.y < -h:
		_roll.position.y = CLIP_H
	elif _roll.position.y > CLIP_H:
		_roll.position.y = -h
	# Fondu des lignes près des bords haut et bas.
	for c in _roll.get_children():
		var ci := c as Control
		var y := _roll.position.y + ci.position.y + ci.size.y * 0.5
		var a := clampf(y / EDGE, 0.0, 1.0) * clampf((CLIP_H - y) / EDGE, 0.0, 1.0)
		ci.modulate.a = a * a * (3.0 - 2.0 * a)


func _input(event: InputEvent) -> void:
	_wheel(event)


func _wheel(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.pressed:
		var mb := event as InputEventMouseButton
		if mb.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			_roll.position.y -= 40.0
		elif mb.button_index == MOUSE_BUTTON_WHEEL_UP:
			_roll.position.y += 40.0


## Position de défilement (pour les tests).
func scroll_y() -> float:
	return _roll.position.y


func back() -> void:
	menu.go_back()
